version: '2'

networks:
  roachnet:

services:
  prometheus:
    image: prom/prometheus:v1.7.0
    container_name: metrics_server
    ports:
      - "9090:9090"

  roach_a:
    image: cockroachdb/cockroach:v1.0.1
    container_name: roach_a
    networks:
      roachnet:
        aliases:
          - roach_a
    ports:
      - "8080:8080"
      - "26257:26257"
    command: start --insecure

  roach_b:
    image: cockroachdb/cockroach:v1.0.1
    container_name: roach_b
    networks:
      roachnet:
        aliases:
          - roach_b
    command: start --insecure --join=roach_a

  roach_c:
    image: cockroachdb/cockroach:v1.0.1
    container_name: roach_c
    networks:
      roachnet:
        aliases:
          - roach_c
    command: start --insecure --join=roach_a
